apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app: {{ name }}
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: {{ name }}
  template:
    metadata:
      labels:
        app: {{ name }}
    spec:
      containers:
        - name: {{ container_name }}
          image: {{ image }}
          ports:
            - containerPort: {{ port }}
          resources:
            requests:
              memory: "{{ memory_request }}"
              cpu: "{{ cpu_request }}"
            limits:
              memory: "{{ memory_limit }}"
              cpu: "{{ cpu_limit }}"
          {% if liveness_probe %}
          livenessProbe:
            httpGet:
              path: {{ liveness_probe.path }}
              port: {{ liveness_probe.port }}
            initialDelaySeconds: {{ liveness_probe.initialDelaySeconds }}
            periodSeconds: {{ liveness_probe.periodSeconds }}
          {% endif %}
          {% if readiness_probe %}
          readinessProbe:
            httpGet:
              path: {{ readiness_probe.path }}
              port: {{ readiness_probe.port }}
            initialDelaySeconds: {{ readiness_probe.initialDelaySeconds }}
            periodSeconds: {{ readiness_probe.periodSeconds }}
          {% endif %}
          {% if env_vars %}
          env:
          {% for name, value in env_vars.items() %}
          - name: {{ name }}
            value: "{{ value }}"
          {% endfor %}
          {% endif %}