apiVersion: v1
kind: Service
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    app: {{ name }}
spec:
  selector:
    app: {{ name }}
  ports:
    - port: {{ port }}
      targetPort: {{ target_port }}
      {% if node_port %}
      nodePort: {{ node_port }}
      {% endif %}
  type: {{ service_type }}